select
    playerid::varchar || '_' || year::varchar as player_year_id,
    playerid::varchar as player_id,
    name::varchar as player_name,
    year::int as year,
    eligibleslots::varchar [] as eligible_slots,
    proteam::varchar as nfl_team,
    position::varchar as position_slot,
    (position::varchar in array_value('WR', 'RB', 'TE')) as is_flex,
    injured::bool as is_injured,
    total_points::double as total_points,
    avg_points::double as avg_points,
    projected_total_points::double as projected_total_points,
    projected_avg_points::double as projected_avg_points,
    percent_owned::double as percent_owned,
    percent_started::double as percent_started,
    stats as stats_raw,
    try_cast(posrank as int) as position_rank,
    if(injurystatus != '[]', replace(injurystatus::varchar, '"', '')::varchar, null) as injury_status,
    meta__source_path::varchar as meta__source_path,
    meta__date_effective::date as meta__date_effective,
    meta__date_pulled::date as meta__date_pulled
from {{ source("s001", "players") }}
