---
services:
  backend:
    environment:
      ACCESS_TOKEN: "${ACCESS_TOKEN}"
      LEAGUE_ID: "${LEAGUE_ID}"
      SWID: "${SWID}"
      ESPN_S2: "${ESPN_S2}"
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
    depends_on:
      - db
    ports:
      - 8000:8000
    links:
      - db
    build: 
      context: .
      dockerfile: ./backend/images/fantasy-footballer/image/Dockerfile
  db:
    image: postgres:14.8-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports: 
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./backend/src/fantasy_footballer/database/initialize_tables.sql:/docker-entrypoint-initdb.d/initialize_tables.sql
      - ./backend/src/fantasy_footballer/database/fill_tables.py:/docker-entrypoint-initdb.d/fill_tables.py
volumes:
  db:
    driver: local
  # frontend:
  #   ports: 
  #     - 3000:3000
  #   entrypoint: ["npm", "start"]
  #   build:
  #     context: .
  #     dockerfile: ./frontend/image/Dockerfile
      