services:
  app:
    environment:
      ACCESS_TOKEN: "${ACCESS_TOKEN}"
      LEAGUE_ID: "${LEAGUE_ID}"
      SWID: "${SWID}"
      ESPN_S2: "${ESPN_S2}"
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
    depends_on:
      - db
    ports:
      - 8080:8080
    expose:
      - 8080
    links:
      - db
    build:
      context: .
      dockerfile: ./images/fantasy-footballer/image/Dockerfile
  db:
    image: postgres:15.7-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports: 
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data/
volumes:
  db:
    driver: local
