---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-added-large-files

      - id: mixed-line-ending
        alias: check-line-endings
        name: check-line-endings
        args: ['--fix=no']

      - id: check-yaml
        exclude: 'cfn\.ya?ml$'

  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        exclude: (__init__|setup|(docs?|examples?|tests?|utils?)/.*)\.py$
        additional_dependencies: ["toml"]
  - repo: "https://github.com/PyCQA/pylint"
    rev: v2.13.8
    hooks:
      - id: pylint
        exclude: (__init__|setup|(docs?|examples?|tests?|utils?)/.*)\.py$
  - repo: "https://github.com/pre-commit/mirrors-yapf"
    rev: v0.32.0
    hooks:
      - id: yapf
        additional_dependencies: [toml]
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        additional_dependencies: [toml]