default:
  target: default
  outputs:
    app:
      type: duckdb
      path: ./resources/fantasy_footballer.duckdb
      keep_open: false
    default:
      type: duckdb
      path: ../../resources/fantasy_footballer.duckdb
