default:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: ./resources/fantasy_footballer.duckdb
      keep_open: false
pre-commit:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: ../../resources/fantasy_footballer.duckdb
