version: 2

sources:
  - name: s001
    tables:
      - name: players
        columns:
          - name: playerId
            data_tests:
              - not_null
          - name: name
            data_tests:
              - not_null
          - name: year
            data_tests:
              - not_null
          - name: posRank
            data_tests:
              - not_null
          - name: eligibleSlots
            data_tests:
              - not_null
          - name: proTeam
            data_tests:
              - not_null
          - name: onTeamId
            data_tests:
              - not_null
          - name: position
            data_tests:
              - not_null
          - name: injuryStatus
          - name: injured
            data_tests:
              - not_null
          - name: total_points
            data_tests:
              - not_null
          - name: avg_points
            data_tests:
              - not_null
          - name: projected_total_points
            data_tests:
              - not_null
          - name: projected_avg_points
            data_tests:
              - not_null
          - name: percent_owned
            data_tests:
              - not_null
          - name: percent_started
            data_tests:
              - not_null
          - name: meta__source_path
            data_tests:
              - not_null
          - name: meta__date_effective
            data_tests:
              - not_null
          - name: meta__date_pulled
            data_tests:
              - not_null

      - name: teams
        columns:
          - name: owners
          - name: team_abbrev
            data_tests:
              - not_null
          - name: team_name
            data_tests:
              - not_null
          - name: division_id
            data_tests:
              - not_null
          - name: division_name
            data_tests:
              - not_null
          - name: wins
            data_tests:
              - not_null
          - name: losses
            data_tests:
              - not_null
          - name: ties
            data_tests:
              - not_null
          - name: points_for
            data_tests:
              - not_null
          - name: points_against
            data_tests:
              - not_null
          - name: acquisitions
            data_tests:
              - not_null
          - name: acquisition_budget_spent
            data_tests:
              - not_null
          - name: drops
            data_tests:
              - not_null
          - name: trades
            data_tests:
              - not_null
          - name: playoff_pct
            data_tests:
              - not_null
          - name: draft_projected_rank
            data_tests:
              - not_null
          - name: streak_length
            data_tests:
              - not_null
          - name: streak_type
            data_tests:
              - not_null
          - name: standing
            data_tests:
              - not_null
          - name: final_standing
            data_tests:
              - not_null
          - name: meta__source_path
            data_type: varchar
            data_tests:
              - not_null
          - name: meta__date_effective
            data_type: date
            data_tests:
              - not_null
          - name: meta__date_pulled
            data_type: date
            data_tests:
              - not_null

      - name: matchups
        columns:
          - name: year
            data_tests:
              - not_null
          - name: matchup_week
            data_tests:
              - not_null
          - name: home_team
            data_tests:
              - not_null
          - name: home_score
            data_tests:
              - not_null
          - name: home_projected
          - name: away_team
          - name: away_score
            data_tests:
              - not_null
          - name: away_projected
          - name: home_lineup
          - name: away_lineup
            data_tests:
              - not_null
          - name: is_playoff
            data_tests:
              - not_null
          - name: matchup_type
            data_tests:
              - not_null
          - name: meta__source_path
            data_type: varchar
          - name: meta__date_effective
            data_type: date
          - name: meta__date_pulled
            data_type: date

      - name: settings
        description: League configuration and settings including scoring rules, roster positions, and playoff structure
        columns:
          - name: year
            data_tests:
              - not_null
          - name: reg_season_count
            description: Number of regular season weeks
            data_type: integer
          - name: matchup_periods
            description: Mapping of matchup periods to week numbers (JSON/struct)
            data_type: json
          - name: veto_votes_required
            description: Number of votes required to veto a trade
            data_type: integer
          - name: team_count
            description: Total number of teams in the league
            data_type: integer
          - name: playoff_team_count
            description: Number of teams that make the playoffs
            data_type: integer
          - name: keeper_count
            description: Number of keeper players allowed per team
            data_type: integer
          - name: trade_deadline
            description: Trade deadline timestamp (Unix milliseconds)
            data_type: bigint
          - name: division_map
            description: Mapping of division IDs to division names (JSON/struct)
            data_type: json
          - name: name
            description: League name
            data_type: varchar
          - name: tie_rule
            description: Rule for handling ties in regular season matchups
            data_type: varchar
          - name: playoff_tie_rule
            description: Rule for handling ties in playoff matchups
            data_type: varchar
          - name: playoff_matchup_period_length
            description: Number of weeks per playoff matchup
            data_type: integer
          - name: playoff_seed_tie_rule
            description: Tiebreaker rule for determining playoff seeding
            data_type: varchar
          - name: scoring_type
            description: League scoring type (e.g., H2H_POINTS, H2H_CATEGORY)
            data_type: varchar
          - name: faab
            description: Whether FAAB (Free Agent Acquisition Budget) is enabled
            data_type: boolean
          - name: scoring_format
            description: Array of scoring rules with stat abbreviations, labels, IDs, and point values
            data_type: json
          - name: position_slot_counts
            description: Roster configuration showing number of slots for each position
            data_type: json
          - name: meta__source_path
            data_type: varchar
          - name: meta__date_effective
            data_type: date
          - name: meta__date_pulled
            data_type: date